# GoReleaser configuration for ncurl
version: 2
project_name: ncurl

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: ncurl
    main: ./cmd/ncurl
    binary: ncurl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

# GoReleaser v2 archive configuration
archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS{{- else }}{{ .Os }}{{- end }}_
      {{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "arm" }}arm_{{ .Arm }}{{- else }}{{ .Arch }}{{- end }}
    formats:
      - tar.gz
      - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# For v2, snapshot configuration is under release
release:
  disable: auto
  draft: false
  prerelease: auto

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*!?:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*!?:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

brews:
  - name: ncurl
    ids:
      - default
    repository:
      owner: stephenbyrne99
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "curl in English - describe HTTP requests in plain language"
    homepage: "https://github.com/stephenbyrne99/ncurl"
    license: "MIT"
    test: |
      system "#{bin}/ncurl", "--version"
    install: |
      bin.install "ncurl"